# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{nested_scaffold}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Akira Matsuda"]
  s.date = %q{2010-12-12}
  s.description = %q{Nested scaffold generator for Rails 3}
  s.email = %q{ronnie@dio.jp}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/generators/USAGE",
    "lib/generators/active_record/active_record_generator.rb",
    "lib/generators/base.rb",
    "lib/generators/erb/erb_generator.rb",
    "lib/generators/erb/templates/_form.html.erb",
    "lib/generators/erb/templates/edit.html.erb",
    "lib/generators/erb/templates/index.html.erb",
    "lib/generators/erb/templates/new.html.erb",
    "lib/generators/erb/templates/show.html.erb",
    "lib/generators/haml/haml_generator.rb",
    "lib/generators/haml/templates/_form.html.haml",
    "lib/generators/haml/templates/edit.html.haml",
    "lib/generators/haml/templates/index.html.haml",
    "lib/generators/haml/templates/new.html.haml",
    "lib/generators/haml/templates/show.html.haml",
    "lib/generators/helper/helper_generator.rb",
    "lib/generators/nested_scaffold_generator.rb",
    "lib/generators/scaffold_controller/scaffold_controller_generator.rb",
    "lib/generators/scaffold_controller/templates/controller.rb",
    "lib/generators/stylesheets/stylesheets_generator.rb",
    "lib/generators/test_unit/helper_generator.rb",
    "lib/generators/test_unit/model_generator.rb",
    "lib/generators/test_unit/scaffold_generator.rb",
    "lib/generators/test_unit/templates/functional_test.rb"
  ]
  s.homepage = %q{http://github.com/amatsuda/nested_scaffold}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Nested scaffold generator for Rails 3}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
  end
end

